Repository TeamProject-Farmer/front-end, pull requests merged in 2023-08, with the labels that each got.

#53 주문/결제 페이지 쿠폰, 적립금, 약관동의 구현
  next.config.js
  src/apis/base.ts
  src/apis/order/order.ts
  src/apis/search/search.ts
  src/components/Common/Category/Plant.tsx
  src/components/Common/Category/index.tsx
  src/components/Common/Header/FirstBuyEvent.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Home/BestReview/styles.ts
  src/components/Home/News/index.tsx
  src/components/Home/Slider/SliderContent.tsx
  src/components/Home/Slider/index.tsx
  src/components/Order/Agreement/index.tsx
  src/components/Order/Delivery/index.tsx
  src/components/Order/InputField/Button.tsx
  src/components/Order/InputField/CheckBoxInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/InputField/styles.ts
  src/components/Order/Payment/index.tsx
  src/components/Order/styles.ts
  src/components/Search/SearchContainer/index.tsx
  src/hooks/order/useCheckBox.ts
  src/hooks/order/useDiscount.ts
  src/pages/layout.tsx
  src/pages/order/index.tsx
  src/pages/search/index.tsx
  src/types/order/types.ts
Labels: 📦 component

#54 bestReview 컴포넌트 슬라이더 구현
  package-lock.json
  package.json
  public/assets/images/home/bestPlantNextBtn.svg
  public/assets/images/home/bestPlantPrevBtn.svg
  src/apis/home/home.ts
  src/components/Home/BestPlant/Plant.tsx
  src/components/Home/BestPlant/index.tsx
  src/components/Home/BestPlant/styles.ts
  src/components/Home/BestReview/Review.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Home/ShopBySize/index.tsx
  src/components/Home/Slider/Indicator.tsx
  src/components/Home/Slider/SliderContent.tsx
  src/components/Home/Slider/index.tsx
  src/types/home/types.ts
Labels: 📦 component

#56 결제 요청 로직 구현
  src/apis/order/order.ts
  src/components/Common/Category/index.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Order/Delivery/index.tsx
  src/components/Order/InputField/Button.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/InputField/styles.ts
  src/components/Order/List/ProductList.tsx
  src/components/Order/PayMethod/PayMethodList.tsx
  src/components/Order/PayMethod/index.tsx
  src/components/Order/Payment/index.tsx
  src/hooks/order/useDiscount.ts
  src/hooks/order/usePayment.ts
  src/pages/layout.tsx
  src/pages/order/index.tsx
  src/types/order/types.ts
  src/utils/order/formValidation.ts
  src/utils/order/formatPhoneNumber.ts
  src/utils/order/generateOrderNumber.ts
  src/utils/order/optionList.ts
  src/utils/order/payMethod.ts
  src/utils/order/processPayment.ts
  store/index.ts
  store/reducers/orderSlice.ts
Labels: 📦 component

#57 feature/mypage: 마이페이지 전체 기능 구현
  next.config.js
  package-lock.json
  package.json
  public/assets/images/mypage/coupon10.svg
  public/assets/images/mypage/coupon30.svg
  public/assets/images/mypage/freeCoupon.svg
  public/assets/images/mypage/option.svg
  src/apis/mypage/cart.ts
  src/apis/mypage/coupon.ts
  src/apis/mypage/purchase.ts
  src/components/Mypage/Cart/CartButtonBox.tsx
  src/components/Mypage/Cart/CartButtonComponent.tsx
  src/components/Mypage/Cart/CartItems.tsx
  src/components/Mypage/Cart/CartList.tsx
  src/components/Mypage/Cart/CartOrderBox.tsx
  src/components/Mypage/Cart/NoneCartList.tsx
  src/components/Mypage/Cart/OrderCartList.tsx
  src/components/Mypage/EditProfile/InputGroup.tsx
  src/components/Mypage/EditProfile/index.tsx
  src/components/Mypage/Main/PurchasesList/index.tsx
  src/components/Mypage/MyCoupons/Coupons.tsx
  src/components/Mypage/MyCoupons/Header.tsx
  src/components/Mypage/MyCoupons/index.tsx
  src/components/Mypage/MyPlants/index.tsx
  src/components/Mypage/Purchases/Calendar/index.tsx
  src/components/Mypage/Purchases/Calendar/react-datepicker.css
  src/components/Mypage/Purchases/ListCheck/index.tsx
  src/components/Mypage/Purchases/OrderHistory/OrderInfoText.tsx
  src/components/Mypage/Purchases/OrderHistory/OrderItem.tsx
  src/components/Mypage/Purchases/OrderHistory/index.tsx
  src/components/Mypage/Purchases/OrderStatus/index.tsx
  src/components/Mypage/Purchases/SearchOption/index.tsx
  src/components/Mypage/styles.tsx
  src/hooks/formatDate.ts
  src/pages/_app.tsx
  src/pages/mypage/cart.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/purchases.tsx
  src/types/mypage/types.ts
  src/types/redux/types.ts
  src/utils/mypage/coupons.tsx
  src/utils/mypage/myPlantsData.ts
  src/utils/mypage/orderStatusData.ts
  store/index.ts
  store/reducers/cartSlice.ts
  store/reducers/orderProductSlice.ts
Labels: 💡 feature, 🪡 style, 📦 component

#65 Feature/home 수정된 디자인 반영
  package-lock.json
  package.json
  public/assets/images/home/bannerBg0.png
  public/assets/images/home/bannerBg1.png
  public/assets/images/home/bannerBg2.png
  public/assets/images/home/largeBg.png
  public/assets/images/home/mediumBg.png
  public/assets/images/home/newsImage.png
  public/assets/images/home/smallBg.png
  src/apis/home/home.ts
  src/components/Common/Category/Plant.tsx
  src/components/Common/Footer/index.tsx
  src/components/Common/Footer/styles.ts
  src/components/Common/Header/FirstBuyEvent.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/Header/styles.ts
  src/components/Common/Icon/index.tsx
  src/components/Common/IconLoader/index.tsx
  src/components/Common/Menu/index.tsx
  src/components/Common/Menu/styles.ts
  src/components/Common/Product/index.tsx
  src/components/Common/Product/styles.ts
  src/components/Home/BestPlant/Plant.tsx
  src/components/Home/BestPlant/index.tsx
  src/components/Home/BestReview/Review.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Home/BestReview/styles.ts
  src/components/Home/News/index.tsx
  src/components/Home/ShopBySize/index.tsx
  src/components/Home/ShopBySize/styles.ts
  src/components/Home/Slider/index.tsx
  src/components/Search/SearchContainer/index.tsx
  src/components/Search/SearchContent/index.tsx
  src/components/Search/SearchUtils/index.tsx
  src/pages/search/index.tsx
  src/types/common/types.ts
  src/utils/home/category.ts
  store/index.ts
  store/reducers/orderSlice.ts
Labels: 📦 component

#69 feature/mypage : 마이페이지 구현 개선 및 issue 사항 구현
  public/assets/images/mypage/iconSearch.svg
  public/assets/images/mypage/search.svg
  src/apis/base.ts
  src/components/Common/Header/index.tsx
  src/components/Common/Icon/index.tsx
  src/components/Mypage/Main/PurchasesList/index.tsx
  src/components/Mypage/Purchases/Calendar/index.tsx
  src/components/Mypage/Purchases/OrderHistory/OrderItem.tsx
  src/components/Mypage/Purchases/SearchOption/index.tsx
  src/pages/_app.tsx
  src/pages/mypage/index.tsx
  src/types/common/types.ts
  src/utils/login/socialLoginData.ts
  src/utils/mypage/orderStatusData.ts
Labels: 💡 feature, 📦 component

#77 Feature/home 파비콘 추가
  public/favicon.ico
  src/components/Common/Header/EventBanner.tsx
  src/components/Common/Header/index.tsx
  src/pages/layout.tsx
Labels: 📦 component

#79 Feature/search 검색 api 수정
  src/apis/search/search.ts
  src/components/Common/Icon/index.tsx
  src/components/Common/Product/index.tsx
  src/components/Common/Product/styles.ts
  src/components/Search/SearchContent/index.tsx
  src/components/Search/SearchUtils/index.tsx
  src/pages/search/index.tsx
  src/types/common/types.ts
Labels: 📦 component

#80 Feature/order 주문 완료 페이지
  src/apis/base.ts
  src/apis/order/order.ts
  src/components/Mypage/Cart/OrderCartList.tsx
  src/components/Order/Delivery/index.tsx
  src/components/Order/InputField/CheckBoxInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/Payment/index.tsx
  src/components/Shop/DetailPage/Panel.tsx
  src/components/Shop/DetailPage/index.tsx
  src/hooks/order/usePayment.ts
  src/pages/order/index.tsx
  src/pages/order/result.tsx
  src/types/mypage/types.ts
  src/types/order/types.ts
  src/utils/order/formatOrderDate.ts
  src/utils/order/generateOrderNumber.ts
  src/utils/order/generateOrderPayload.ts
  src/utils/order/processPayment.ts
Labels: 📦 component

#81 로그인 토큰값 처리, 결제 기능 완성
  next.config.js
  src/apis/base.ts
  src/apis/login/login.ts
  src/apis/order/order.ts
  src/apis/search/search.ts
  src/components/Common/Header/EventBanner.tsx
  src/components/Home/BestReview/Review.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Home/Slider/Indicator.tsx
  src/components/Mypage/Cart/OrderCartList.tsx
  src/components/Mypage/Main/MyProfile/index.tsx
  src/components/Mypage/Main/TextBanner/index.tsx
  src/components/Mypage/Purchases/Calendar/index.tsx
  src/components/Mypage/Purchases/SearchOption/index.tsx
  src/components/Mypage/styles.tsx
  src/components/Order/Delivery/index.tsx
  src/components/Order/InputField/PaymentInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/List/ProductList.tsx
  src/components/Order/NestedLayout/index.tsx
  src/components/Order/Payment/index.tsx
  src/components/Search/SearchContent/index.tsx
  src/hooks/order/useDiscount.ts
  src/hooks/order/usePayment.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/myplants.tsx
  src/pages/order/index.tsx
  src/pages/order/result.tsx
  src/pages/search/index.tsx
  src/types/home/types.ts
  src/types/order/types.ts
  src/utils/mypage/formatDate.ts
  src/utils/mypage/navbar.ts
  src/utils/order/generateOrderNumber.ts
  src/utils/order/generateOrderPayload.ts
  src/utils/order/optionList.ts
  src/utils/order/processPayment.ts
  store/index.ts
  store/reducers/userSlice.ts
Labels: 📦 component

#82 Feature/shop: 파일 리펙토링 및 구매,장바구니 기능 추가
  src/apis/shop/product.ts
  src/apis/shop/qna.ts
  src/components/Common/Category/styles.ts
  src/components/Mypage/Cart/NoneCartList.tsx
  src/components/Shop/BySize/index.tsx
  src/components/Shop/Common/ProductWrapper/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/MyQnA.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/MyQnA.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/OnOffButton.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/QnAWrapper.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/SingleReview.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/StarOption.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/index.tsx
  src/components/Shop/DetailPage/Panel.tsx
  src/components/Shop/DetailPage/Panel/PayInfo.tsx
  src/components/Shop/DetailPage/Panel/ProductInfo.tsx
  src/components/Shop/DetailPage/Panel/index.tsx
  src/components/Shop/DetailPage/PreviewPhoto/index.tsx
  src/components/Shop/DetailPage/index.tsx
  src/components/Shop/ShopDetail/index.tsx
  src/types/shop/apiTypes.ts
  src/types/shop/types.ts
  src/utils/shop/handlePrice.ts
  src/utils/shop/handleShipDay.ts
  store/index.ts
  store/reducers/orderDataSlice.ts
  store/reducers/orderSlice.ts
Labels: 💡 feature, 🪡 style, 🛠 refactor
