Repository TeamProject-Farmer/front-end, pull requests merged in 2023-09, with the labels that each got.

#89 Feature/shop: react-query 적용, FirstCoupon 위치 이동
  package-lock.json
  package.json
  src/apis/shop/product.ts
  src/apis/shop/qna.ts
  src/apis/shop/review.ts
  src/components/Shop/BySize/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/MyQnA.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/SingleReview.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/index.tsx
  src/components/Shop/FirstCoupon/index.tsx
  src/components/Shop/ShopDetail/MDPick.tsx
  src/components/Shop/ShopDetail/index.tsx
  src/pages/shop/coupon/index.tsx
  src/utils/shop/shipmentNotice.ts
Labels: 🔋 fix

#93 소셜 로그인 오류 수정
  src/apis/shop/product.ts
  src/components/Login/InputGroup/index.tsx
  src/components/Login/SocialLogin/index.tsx
  src/pages/login/index.tsx
  src/utils/login/socialLoginData.ts
  src/utils/token/getNewTokens.ts
Labels: 🐞 bug

#96 feat: refreshToken 삭제 수정
  src/components/Common/Header/EventBanner.tsx
  src/components/Common/Header/index.tsx
  src/middleware.ts
  src/utils/login/socialLoginData.ts
  src/utils/token/getNewTokens.ts
Labels: 🐞 bug

#98 로그인 미들웨어 재설정
  src/apis/base.ts
  src/apis/mypage/purchase.ts
  src/components/Login/SocialLogin/index.tsx
  src/components/Mypage/EditProfile/index.tsx
  src/components/Mypage/Layout/Navbar/index.tsx
  src/components/Mypage/Purchases/ListCheck/index.tsx
  src/components/Mypage/Purchases/OrderHistory/index.tsx
  src/components/Mypage/Purchases/OrderStatus/index.tsx
  src/components/Mypage/Purchases/SearchOption/index.tsx
  src/components/Mypage/styles.tsx
  src/components/Order/InputField/PaymentInput.tsx
  src/components/Order/InputField/index.tsx
  src/middleware.ts
  src/pages/mypage/cart.tsx
  src/pages/order/index.tsx
  src/types/mypage/types.ts
  src/utils/order/processPayment.ts
  src/utils/token/renewTokens.ts
  src/utils/token/validateTokens.ts
Labels: 🔋 fix

#99 test: 소셜 로그인 테스트
  src/apis/base.ts
  src/components/Common/Header/index.tsx
  src/components/Login/InputGroup/index.tsx
  src/components/Login/SocialLogin/index.tsx
  src/components/Mypage/Main/PurchasesList/index.tsx
  src/components/Mypage/styles.tsx
  src/pages/mypage/index.tsx
  src/utils/cookie/index.ts
  src/utils/mypage/navbar.ts
Labels: 🔋 fix

#97 Feature/shop: pages로 데이터 합침, react-query 호출 수정
  src/components/Shop/BySize/index.tsx
  src/components/Shop/Common/GaugeBox/EachStarGauge.tsx
  src/components/Shop/Common/GaugeBox/TotalStarGauge.tsx
  src/components/Shop/Common/GaugeBox/styles.tsx
  src/components/Shop/Common/OptionBars/OrderBar.tsx
  src/components/Shop/Common/OptionBars/SizeBar.tsx
  src/components/Shop/Common/OptionBars/SortBar.tsx
  src/components/Shop/Common/Pagination/index.tsx
  src/components/Shop/Common/ProductWrapper/index.tsx
  src/components/Shop/Common/SideAd/index.tsx
  src/components/Shop/Common/SmallParts/VerticalLine.tsx
  src/components/Shop/Common/SmallProduct.tsx
  src/components/Shop/DetailPage/ContentWrapper/DetailImage/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/Notice/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/ContentOptionBox.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/PanelOptionBox.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/styles.ts
  src/components/Shop/DetailPage/ContentWrapper/QnA/MyQnA.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/OnOffButton.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/QnAWrapper.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/QnA/styles.ts
  src/components/Shop/DetailPage/ContentWrapper/Review/SingleReview.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/StarOption.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/Review/styles.ts
  src/components/Shop/DetailPage/ContentWrapper/index.tsx
  src/components/Shop/DetailPage/NoProduct/index.tsx
  src/components/Shop/DetailPage/Panel/PayInfo.tsx
  src/components/Shop/DetailPage/Panel/ProductInfo.tsx
  src/components/Shop/DetailPage/Panel/index.tsx
  src/components/Shop/DetailPage/Panel/styles.ts
  src/components/Shop/DetailPage/PreviewPhoto/index.tsx
  src/components/Shop/DetailPage/index.tsx
  src/components/Shop/EventDetail/index.tsx
  src/components/Shop/FirstCoupon/index.tsx
  src/components/Shop/ShopDetail/index.tsx
  src/components/Shop/index.tsx
  src/components/Shop/styles.ts
  src/hooks/shop/useOptionBox.ts
  src/hooks/shop/usePanelStars.ts
  src/pages/shop/[category].tsx
  src/pages/shop/bysize/[size].tsx
  src/pages/shop/coupon/index.tsx
  src/pages/shop/detail/[detail].tsx
  src/pages/shop/event/[detail].tsx
  src/pages/shop/index.tsx
  src/types/shop/types.ts
  src/utils/register/scrollUp.ts
  src/utils/shop/checkIsMember.ts
  src/utils/shop/handleClipBoard.ts
Labels: 🔋 fix

#108 구매 목록 날짜 세팅 수정
  src/apis/mypage/purchase.ts
  src/components/Login/InputGroup/index.tsx
  src/components/Mypage/Purchases/SearchOption/index.tsx
  src/components/Search/SearchContainer/index.tsx
  src/pages/mypage/purchases.tsx
  src/pages/search/index.tsx
  src/utils/login/setUser.ts
Labels: 🔋 fix

#109 feat: 구매 목록 날짜 검색 버튼 클릭 시 함수 호출
  src/components/Mypage/Purchases/Calendar/index.tsx
  src/pages/mypage/purchases.tsx
Labels: 🔋 fix

#112 Feature/#110 board: admin layout style 수정, home file rename
  src/components/Admin/AdminLayout/index.tsx
  src/components/Admin/Common/CurrentTime/index.tsx
  src/components/Admin/Home/Analytics/index.tsx
  src/components/Admin/Home/Todo/index.tsx
  src/components/Admin/Home/index.tsx
  src/components/Admin/styles.ts
  src/components/Home/Common/Title.tsx
  src/pages/admin/index.tsx
  src/pages/adminlayout.tsx
Labels: 🪡 style

#113 Admin Title 재수정
  src/components/Home/Common/Title.tsx
  src/pages/admin/index.tsx
  src/pages/adminlayout.tsx
Labels: 🔋 fix

#115 Feature/shop: 리뷰 모달, 장바구니 추가 수정
  public/assets/images/shop/sideAdImage.svg
  public/assets/images/shop/sideAdImg.svg
  src/apis/shop/product.ts
  src/components/Common/Modal/ReviewModal.tsx
  src/components/Mypage/Layout/Navbar/index.tsx
  src/components/Mypage/styles.tsx
  src/components/Shop/Common/SideAd/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox/index.tsx
  src/hooks/shop/useOptionBox.ts
  src/pages/mypage/purchases.tsx
  src/types/shop/apiTypes.ts
  src/utils/shop/sortOption.ts
Labels: 🔋 fix
