Repository TeamProject-Farmer/front-end, pull requests merged in 2023-07, with the labels that each got.

#27 Feature/mypage: 피그마기준 마이페이지 전체 UI 구현(+일부 기능 구현)
  package-lock.json
  public/assets/images/mypage/button.svg
  public/assets/images/mypage/call.svg
  public/assets/images/mypage/coupon10.svg
  public/assets/images/mypage/coupon30.svg
  public/assets/images/mypage/freeCoupon.svg
  public/assets/images/mypage/mail.svg
  public/assets/images/mypage/more.svg
  public/assets/images/mypage/option.svg
  public/assets/images/mypage/profile.svg
  public/assets/images/mypage/search.svg
  src/components/Home/Footer/styles.ts
  src/components/Home/Header/index.tsx
  src/components/Home/Header/styles.ts
  src/components/Mypage/EditProfile/InputGroup.tsx
  src/components/Mypage/EditProfile/index.tsx
  src/components/Mypage/Layout/Navbar/index.tsx
  src/components/Mypage/Layout/layout.tsx
  src/components/Mypage/Main/MyProfile/Icon.tsx
  src/components/Mypage/Main/MyProfile/index.tsx
  src/components/Mypage/Main/PurchasesList/index.tsx
  src/components/Mypage/Main/TextBanner/index.tsx
  src/components/Mypage/MyCoupons/index.tsx
  src/components/Mypage/MyPlants/ProgressBar.tsx
  src/components/Mypage/MyPlants/Weekdays.tsx
  src/components/Mypage/MyPlants/index.tsx
  src/components/Mypage/Purchases/ListCheck/index.tsx
  src/components/Mypage/Purchases/OrderHistory/OrderInfoText.tsx
  src/components/Mypage/Purchases/OrderHistory/OrderItem.tsx
  src/components/Mypage/Purchases/OrderHistory/index.tsx
  src/components/Mypage/styles.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/mycoupons.tsx
  src/pages/mypage/myplants.tsx
  src/pages/mypage/profile.tsx
  src/pages/mypage/purchases.tsx
  src/styles/globalStyle.tsx
  src/styles/theme.tsx
  src/types/mypage/types.ts
  src/utils/mypage/coupons.tsx
  src/utils/mypage/navbar.ts
  src/utils/mypage/orderTimeList.ts
  src/utils/mypage/weekdays.ts
Labels: 💡 feature, 🪡 style, 📦 component

#31 검색 페이지, 주문/결제 페이지 UI 작업 완료
  package-lock.json
  src/components/Home/Common/Icon.tsx
  src/components/Home/Footer/index.tsx
  src/components/Home/Footer/styles.ts
  src/components/Order/InputField/Button.tsx
  src/components/Order/InputField/CheckBoxInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/InputField/styles.ts
  src/components/Order/InputGroup/index.tsx
  src/components/Order/Layout/index.tsx
  src/components/Order/List/PaymentList.tsx
  src/components/Order/List/ProductList.tsx
  src/components/Order/styles.ts
  src/components/Search/Keyword/index.tsx
  src/components/Search/Layout/index.tsx
  src/components/Search/SearchContainer/index.tsx
  src/components/Search/SearchContent/Plant.tsx
  src/components/Search/SearchContent/index.tsx
  src/components/Search/SearchUtils/index.tsx
  src/pages/order/index.tsx
  src/pages/search/index.tsx
  src/styles/theme.tsx
  src/types/home/types.ts
  src/types/order/types.ts
  src/types/search/types.ts
Labels: 📍 plan

#29 Feature/register: 회원가입 페이지 변경사항 반영
  src/apis/register/join.ts
  src/components/Register/InputGroup/index.tsx
  src/types/register/types.ts
  src/utils/register/formUtil.ts
Labels: 🪡 style, 📦 component

#32 검색 페이지, 주문/결제 페이지 UI 작업 완료
  package-lock.json
  src/components/Home/Common/Icon.tsx
  src/components/Home/Footer/index.tsx
  src/components/Home/Footer/styles.ts
  src/components/Order/InputField/Button.tsx
  src/components/Order/InputField/CheckBoxInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/InputField/styles.ts
  src/components/Order/InputGroup/index.tsx
  src/components/Order/Layout/index.tsx
  src/components/Order/List/PaymentList.tsx
  src/components/Order/List/ProductList.tsx
  src/components/Order/styles.ts
  src/components/Search/Keyword/index.tsx
  src/components/Search/Layout/index.tsx
  src/components/Search/SearchContainer/index.tsx
  src/components/Search/SearchContent/Plant.tsx
  src/components/Search/SearchContent/index.tsx
  src/components/Search/SearchUtils/index.tsx
  src/pages/order/index.tsx
  src/pages/search/index.tsx
  src/styles/theme.tsx
  src/types/home/types.ts
  src/types/order/types.ts
  src/types/search/types.ts
Labels: 📍 plan

#28 Feature/login: 소셜로그인(네이버, 카카오, 구글) 연동 및 로그인 수정사항 반영
  src/components/Login/KakaoLogin/index.tsx
  src/components/Login/SnsCircles/index.tsx
  src/components/Login/SocialLogin/index.tsx
  src/components/Register/Header/index.tsx
  src/components/Register/SnsCircles/index.tsx
  src/pages/login/google.tsx
  src/pages/login/index.tsx
  src/pages/login/kakao.tsx
  src/pages/login/naver.tsx
  src/types/redux/types.ts
  src/utils/login/socialLoginData.ts
  store/reducers/userSlice.ts
Labels: 💡 feature, 📦 component

#44 Feature/shop
  package-lock.json
  package.json
  src/components/Common/Product/index.tsx
  src/components/Common/Product/styles.ts
  src/components/Common/type.ts
  src/components/Shop/Common/Category/styles.ts
  src/components/Shop/Common/Item.tsx
  src/components/Shop/Common/OrderBar.tsx
  src/components/Shop/Common/SideAd.tsx
  src/components/Shop/Common/styles.tsx
  src/components/Shop/DetailPage/ContentWrapper/OptionBox.tsx
  src/components/Shop/DetailPage/ContentWrapper/SimilarProducts.tsx
  src/components/Shop/DetailPage/ContentWrapper/SingleReview.tsx
  src/components/Shop/DetailPage/ContentWrapper/index.tsx
  src/components/Shop/DetailPage/Panel.tsx
  src/components/Shop/DetailPage/PreviewPhoto.tsx
  src/components/Shop/DetailPage/index.tsx
  src/components/Shop/EventDetail/index.tsx
  src/components/Shop/ShopDetail/index.tsx
  src/components/Shop/index.tsx
  src/components/Shop/type.ts
  src/pages/layout.tsx
  src/pages/shop/[category].tsx
  src/pages/shop/[category]/detail/[detail].tsx
  src/pages/shop/event/[detail].tsx
  src/pages/shop/index.tsx
  src/styles/theme.tsx
Labels: 🪡 style

#47 Feature/mypage: 마이페이지 변경사항 적용 및 token interceptor 구현
  package-lock.json
  src/apis/base.ts
  src/apis/login/login.ts
  src/apis/register/email.ts
  src/apis/register/join.ts
  src/components/Login/SocialLogin/index.tsx
  src/components/Mypage/Layout/Navbar/index.tsx
  store/index.ts
  store/reducers/userSlice.ts
Labels: 📝 documentation, ⚙️ conf

#51 Feature/mypage: 마이페이지 메인 정보 & 수정 기능 구현 및 API 연동
  src/apis/mypage/editProfile.ts
  src/components/Mypage/EditProfile/InputGroup.tsx
  src/components/Mypage/EditProfile/index.tsx
  src/components/Mypage/Main/MyProfile/index.tsx
  src/components/Mypage/styles.tsx
  src/pages/_app.tsx
  src/types/mypage/types.ts
  src/utils/mypage/editForm.ts
Labels: 💡 feature, 📦 component

#48 메인페이지와 검색페이지의 api 작업
  public/assets/images/home/headerLogo.png
  public/assets/images/mypage/search.svg
  public/assets/images/order/checked.svg
  src/apis/base.ts
  src/apis/common/category.ts
  src/apis/home/home.ts
  src/apis/search/search.ts
  src/components/Common/Category/Plant.tsx
  src/components/Common/Category/index.tsx
  src/components/Common/Category/styles.ts
  src/components/Common/Footer/index.tsx
  src/components/Common/Header/FirstBuyEvent.tsx
  src/components/Common/Header/index.tsx
  src/components/Common/IconLoader/index.tsx
  src/components/Common/Product/index.tsx
  src/components/Common/type.ts
  src/components/Home/BestPlant/Plant.tsx
  src/components/Home/BestPlant/index.tsx
  src/components/Home/BestReview/Review.tsx
  src/components/Home/BestReview/index.tsx
  src/components/Home/Category/index.tsx
  src/components/Home/News/index.tsx
  src/components/Home/ShopBySize/index.tsx
  src/components/Home/Slider/Indicator.tsx
  src/components/Home/Slider/SliderContent.tsx
  src/components/Home/Slider/index.tsx
  src/components/Order/Delivery/index.tsx
  src/components/Order/InputField/Button.tsx
  src/components/Order/InputField/CheckBoxInput.tsx
  src/components/Order/InputField/index.tsx
  src/components/Order/InputField/styles.ts
  src/components/Order/InputGroup/index.tsx
  src/components/Order/Payment/index.tsx
  src/components/Order/styles.ts
  src/components/Search/Keyword/index.tsx
  src/components/Search/SearchContainer/index.tsx
  src/components/Search/SearchContent/index.tsx
  src/components/Search/SearchUtils/index.tsx
  src/components/Shop/DetailPage/ContentWrapper/SimilarProducts.tsx
  src/components/Shop/EventDetail/index.tsx
  src/components/Shop/ShopDetail/index.tsx
  src/components/Shop/type.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/layout.tsx
  src/pages/order/index.tsx
  src/pages/search/index.tsx
  src/types/home/types.ts
  src/types/order/types.ts
  src/types/search/types.ts
  src/utils/order/formValidation.ts
  src/utils/search/sortingOptions.ts
  store/index.ts
  store/reducers/bannerSlice.ts
Labels: 💡 feature
